name-template: ComPWA Organization Documentation $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION

references:
  - main
  - epic/*

categories:
  - title: 💡 New features
    label: 💡 Feature
  - title: ⚠️ Interface
    labels:
      - ⚠️ Interface
      - 📖 Physics
  - title: 🐛 Bug fixes
    label: Bug
  - title: 🔨 Internal maintenance
    label: 🔨 Maintenance
  - title: 📝 Documentation
    label: 📝 Docs
  - title: 🖱️ Developer Experience
    label: 🖱️ DX

change-template: "- $TITLE (#$NUMBER)"

replacers:
  - search: /([a-z]+!?:\s*)(.*)/g
    replace: $2

sort-direction: ascending

template: |
  _See all documentation on [compwa-org.rtfd.io](https://compwa-org.rtfd.io)._

  $CHANGES
