ci:
  autoupdate_commit_msg: "MAINT: update pip constraints and pre-commit"
  autoupdate_schedule: quarterly
  skip:
    - check-jsonschema
    - pin-nb-requirements
    - pyright

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/ComPWA/policy
    rev: 0.4.1
    hooks:
      - id: check-dev-files
        args:
          - --doc-apt-packages=graphviz
          - --dev-python-version=3.12
          - --github-pages
          - --imports-on-top
          - --no-prettierrc
          - --pin-requirements=bimonthly
          - --repo-name=compwa.github.io
          - --repo-title=ComPWA Organization
      - id: colab-toc-visible
      - id: fix-nbformat-version
      - id: remove-empty-tags

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args:
          - --drop-empty-cells
          - --extra-keys
          - |
            cell.attachments
            cell.metadata.code_folding
            cell.metadata.editable
            cell.metadata.id
            cell.metadata.pycharm
            cell.metadata.slideshow
            cell.metadata.user_expressions
            metadata.celltoolbar
            metadata.colab.name
            metadata.colab.provenance
            metadata.interpreter
            metadata.notify_time
            metadata.toc
            metadata.toc-autonumbering
            metadata.toc-showcode
            metadata.toc-showmarkdowntxt
            metadata.toc-showtags
            metadata.varInspector
            metadata.vscode

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi, jupyter]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: >
          (?x)^(
            .*\.bib|
            .*\.svg|
            \.cspell\.json
          )$
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: >
          (?x)^(
            .*\.svg
          )$

  - repo: https://github.com/ComPWA/prettier-pre-commit
    rev: v3.3.3
    hooks:
      - id: prettier

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args: [--in-place]
        exclude: (?x)^(.*/Manifest\.toml|.*/Project\.toml)$

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.2
    hooks:
      - id: check-jsonschema
        name: Check CITATION.cff
        args:
          - --default-filetype
          - yaml
          - --schemafile
          - https://citation-file-format.github.io/1.2.0/schema.json
          - CITATION.cff
        pass_filenames: false

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.13.3
    hooks:
      - id: cspell

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3
    hooks:
      - id: editorconfig-checker
        name: editorconfig
        alias: ec
        exclude: >-
          (?x)^(
            .*\.py
          )$

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        always_run: true
        exclude: >
          (?x)^(
            docs/_static/favicon.ico
          )$

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.0
    hooks:
      - id: nbqa-isort
        args: [--float-to-top]
        exclude: >-
          (?x)^(
            docs/adr/.*\.ipynb|
            docs/report/001\.ipynb|
            docs/report/002\.ipynb|
            docs/report/003\.ipynb|
            docs/report/008\.ipynb|
            docs/report/013\.ipynb|
            docs/report/018\.ipynb|
            docs/report/020\.ipynb|
            docs/report/026\.ipynb|
            docs/report/027\.ipynb|
            docs/report/028\.ipynb|
            docs/symbolics\.ipynb
          )$

  - repo: local
    hooks:
      - id: pin-nb-requirements
        name: Check whether notebook contains a pip install line
        description:
          Specify which packages to install specifically in order to run
          this notebook.
        entry: python3 .pre-commit/pin_nb_requirements.py
        language: system
        types:
          - jupyter

  - repo: https://github.com/ComPWA/mirrors-pyright
    rev: v1.1.379
    hooks:
      - id: pyright
