version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - htmlzip

build:
  os: ubuntu-20.04
  apt_packages:
    - graphviz
  tools:
    python: "3.8"
  commands:
    - pip install -e .[doc] -c .constraints/py3.8.txt
    - cat docs/conf.py
    - sphinx-build --keep-going -TW -b html docs/ _readthedocs/html
