version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - htmlzip

build:
  os: ubuntu-22.04
  apt_packages:
    - graphviz
  tools:
    python: "3.10"
  jobs:
    post_install:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - |-
        /home/docs/.cargo/bin/uv pip install --system -c .constraints/py3.10.txt -e .[doc]
