version: 2

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - htmlzip

build:
  os: ubuntu-22.04
  apt_packages:
    - graphviz
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install -c .constraints/py3.10.txt -e .[doc]
      - |
        wget https://julialang-s3.julialang.org/bin/linux/x64/1.9/julia-1.9.2-linux-x86_64.tar.gz
      - tar xzf julia-1.9.2-linux-x86_64.tar.gz
      - mkdir bin
      - ln -s $PWD/julia-1.9.2/bin/julia bin/julia
      - ./bin/julia docs/InstallIJulia.jl
