name: compwa.github.io
channels:
  - conda-forge
dependencies:
  - graphviz # for binder
  - juliaup
  - pip
  - python==3.10.*
  - pip:
      - -c .constraints/py3.10.txt -e .[dev]
variables:
  PRETTIER_LEGACY_CLI: 1
  PYTHONHASHSEED: 0
