name: compwa-org
channels:
  - defaults
  - conda-forge
dependencies:
  - appmode
  - graphviz # for binder
  - pip
  - python==3.8.*
  - pip:
      - notebook # https://github.com/kirbs-/hide_code/issues/97
      - hide-code
      - |
        -c .constraints/py3.8.txt
        -e .[dev]
