name: compwa.github.io
channels:
  - conda-forge
dependencies:
  - graphviz # for binder
  - juliaup
  - pip
  - python==3.12.*
  - pip:
      - -c .constraints/py3.12.txt -e .[dev]
variables:
  PYTHONHASHSEED: 0
