[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=61.2",
    "setuptools_scm",
]

[project]
authors = [{name = "Common Partial Wave Analysis", email = "compwa-admin@ep1.rub.de"}]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "graphviz",
    "ipympl",
    "matplotlib",
    "mpl-interactions",
]
description = "Source code for the ComPWA Organization pages"
dynamic = ["version"]
license = {text = "GPLv3 or later"}
maintainers = [{email = "compwa-admin@ep1.rub.de"}]
name = "compwa-org"
requires-python = ">=3.7"

[project.optional-dependencies]
dev = [
    "compwa-org[doc]",
    "compwa-org[jupyter]",
    "compwa-org[sty]",
    "compwa-org[test]",
    "sphinx-autobuild",
    "tox >=1.9", # for skip_install, use_develop
]
doc = [
    "Sphinx >=3",
    "myst-nb >=0.14", # nb_ configuration prefixes
    "sphinx-api-relink >=0.0.4",
    "sphinx-book-theme",
    "sphinx-codeautolink[ipython]",
    "sphinx-comments",
    "sphinx-copybutton",
    "sphinx-design",
    "sphinx-hep-pdgref",
    "sphinx-pybtex-etal-style",
    "sphinx-remove-toctrees",
    "sphinx-thebe",
    "sphinx-togglebutton",
    "sphinxcontrib-bibtex >=2",
]
format = ["black"]
jupyter = [
    "compwa-org[doc]",
    "isort",
    "jupyterlab",
    "jupyterlab-code-formatter",
    "jupyterlab-git",
    "jupyterlab-lsp",
    "jupyterlab-myst",
    "python-lsp-ruff",
    "python-lsp-server[rope]",
    'ypy-websocket <0.8.3; python_version <"3.8.0"',
]
lint = ["ruff"]
sty = [
    "attrs", # https://github.com/ComPWA/compwa.github.io/runs/8127821070?check_suite_focus=true#step:5:52
    "compwa-org[format]",
    "compwa-org[lint]",
    "nbformat",
    "pre-commit >=1.4.0",
    "sphinx-api-relink >=0.0.4",
]
test = [
    "jupyter",
    "nbmake",
    'nbmake <1.3; python_version=="3.7.*"',
]

[project.readme]
content-type = "text/markdown"
file = "README.md"

[project.urls]
Documentation = "https://compwa.github.io"
Source = "https://github.com/ComPWA/compwa.github.io"
Tracker = "https://github.com/ComPWA/compwa.github.io/issues"

[tool.setuptools]
include-package-data = false

[tool.setuptools_scm]
write_to = "version.py"

[tool.black]
exclude = '''
/(
    .*\.egg-info
    | .*build
    | \.eggs
    | \.git
    | \.pytest_cache
    | \.tox
    | \.venv
    | \.vscode
    | dist
)/
'''
include = '\.pyi?$'
preview = true
target-version = [
    "py310",
    "py311",
    "py312",
    "py37",
    "py38",
    "py39",
]

[tool.pyright]
exclude = [
    "**/.git",
    "**/.ipynb_checkpoints",
    "**/.mypy_cache",
    "**/.pytest_cache",
    "**/.tox",
    "**/__pycache__",
    "**/_build",
]
reportGeneralTypeIssues = false
reportIncompatibleMethodOverride = false
reportMissingParameterType = false
reportMissingTypeArgument = false
reportMissingTypeStubs = false
reportOverlappingOverload = false
reportPrivateImportUsage = false
reportPrivateUsage = false
reportUnboundVariable = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUnnecessaryComparison = false
reportUnnecessaryContains = false
reportUnnecessaryIsInstance = false
reportUntypedFunctionDecorator = false
reportUnusedClass = true
reportUnusedFunction = true
reportUnusedImport = true
reportUnusedVariable = true
typeCheckingMode = "strict"

[tool.pytest.ini_options]
addopts = [
    "--color=yes",
    "--durations=0",
    "--ignore-glob=*/.ipynb_checkpoints/*",
    "--ignore=docs/adr/001/sympy.ipynb",
    "--ignore=docs/conf.py",
    "--nbmake-timeout=1200",
    "-k='not docs/report/019.ipynb'",
]
filterwarnings = [
    "error",
    "ignore:Passing a schema to Validator.iter_errors is deprecated.*:DeprecationWarning",
    "ignore:The .* argument to NotebookFile is deprecated.*:pytest.PytestRemovedIn8Warning",
    "ignore:open_text is deprecated.*:DeprecationWarning",
    "ignore:read_text is deprecated.*:DeprecationWarning",
    "ignore:unclosed .*:ResourceWarning",
]
norecursedirs = ["_build"]
testpaths = ["docs"]

[tool.ruff]
extend-include = ["*.ipynb"]
extend-select = [
    "A",
    "B",
    "BLE",
    "C4",
    "C90",
    "D",
    "EM",
    "ERA",
    "FA",
    "I",
    "ICN",
    "INP",
    "ISC",
    "N",
    "NPY",
    "PGH",
    "PIE",
    "PL",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "T20",
    "TCH",
    "TID",
    "TRY",
    "UP",
    "YTT",
]
ignore = [
    "D101",
    "D102",
    "D103",
    "D105",
    "D107",
    "D203",
    "D213",
    "D407",
    "D416",
    "E501",
    "SIM108",
]
show-fixes = true
target-version = "py37"
task-tags = ["cspell"]

[tool.ruff.per-file-ignores]
"**/024.ipynb" = ["E731", "E741", "PGH001", "S307"]
"**/025.ipynb" = ["E731"]
"*.ipynb" = [
    "A003",
    "B008",
    "B018",
    "C408",
    "C90",
    "D",
    "E402",
    "E703",
    "F404",
    "N802",
    "N803",
    "N806",
    "N807",
    "N815",
    "N816",
    "PLR09",
    "PLR2004",
    "PLW0602",
    "PLW0603",
    "PLW2901",
    "S101",
    "T20",
    "TCH00",
]
"docs/*" = [
    "D",
    "E402",
    "INP001",
    "S101",
    "S113",
    "T201",
]
"docs/conf.py" = [
    "A001",
    "D100",
    "PLW2901",
]
"docs/report/002.ipynb" = ["F821"]
"docs/report/003.ipynb" = ["F821"]
"docs/report/005.ipynb" = ["F821"]
"docs/report/011.ipynb" = ["F821"]
"docs/report/020.ipynb" = ["F821"]
"docs/report/022.ipynb" = ["F821"]
"docs/report/024.ipynb" = ["F821", "S102"]
"setup.py" = ["D100"]

[tool.ruff.pydocstyle]
convention = "google"

[tool.tomlsort]
all = false
ignore_case = true
in_place = true
sort_first = [
    "build-system",
    "project",
    "tool.setuptools",
    "tool.setuptools_scm",
]
sort_table_keys = true
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
