name: pytest-notebook

on:
  push:
    branches:
      - main
      - epic/*
  pull_request:
    branches:
      - main
      - epic/*

jobs:
  pytest:
    name: Test modified notebooks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Check modified notebooks
        id: diff
        run: |
          git diff --name-only origin/$GITHUB_BASE_REF --output=diff.txt -- docs/**.ipynb
          echo "::set-output name=modified-notebooks::$(cat diff.txt)"
      - name: Set up Python ${{ matrix.python-version }}
        if: steps.diff.outputs.modified-notebooks != ''
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        if: steps.diff.outputs.modified-notebooks != ''
        run: |
          sudo apt-get -y install graphviz
          pip install -c .constraints/py3.7.txt .[test]
      - name: Run notebooks with pytest (diff only)
        if: steps.diff.outputs.modified-notebooks != ''
        run: pytest --nbmake $(cat diff.txt)
