name: pytest-notebook

on:
  pull_request:
    branches:
      - main
      - epic/*

jobs:
  pytest:
    name: Test modified notebooks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Check modified notebooks
        id: diff
        run: |
          git diff --name-only origin/$GITHUB_BASE_REF --output=diff.txt -- docs/**.ipynb
          echo "::set-output name=modified-notebooks::$(cat diff.txt)"
      - run: cat diff.txt
      - uses: actions/setup-python@v4
        if: steps.diff.outputs.modified-notebooks != ''
        with:
          python-version: "3.8"
      - name: Install dependencies
        if: steps.diff.outputs.modified-notebooks != ''
        run: |
          sudo apt-get -y install graphviz
          pip install -c .constraints/py3.8.txt .[test]
      - name: Run notebooks with pytest (diff only)
        if: steps.diff.outputs.modified-notebooks != ''
        run: |
          case $(pytest --nbmake --nbmake-timeout=1200 $(cat diff.txt)) in
            0|5) exit 0;;
            *) exit $1;;
          esac
        # cspell:ignore esac
