name: pytest-notebook

on:
  pull_request:
    branches:
      - main
      - epic/*

jobs:
  pytest:
    name: Test modified notebooks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Check modified notebooks
        id: diff
        run: |
          git diff --name-only origin/$GITHUB_BASE_REF --output=diff.txt -- docs/**.ipynb
          echo "::set-output name=modified-notebooks::$(cat diff.txt)"
      - run: cat diff.txt
      - uses: actions/setup-python@v4
        if: steps.diff.outputs.modified-notebooks != ''
        with:
          python-version: "3.8"
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.7 # should match notebook kernel name
      - name: Install dependencies
        if: steps.diff.outputs.modified-notebooks != ''
        run: |
          julia -e 'import Pkg; Pkg.add("IJulia")'
          sudo apt-get -y install graphviz
          pip install -c .constraints/py3.8.txt .[test]
      - name: Install IJulia kernel
        run: |
          julia -e 'using IJulia; installkernel("julia")'
        # cspell:ignore installkernel
      - name: Run notebooks with pytest (diff only)
        if: steps.diff.outputs.modified-notebooks != ''
        run: pytest --nbmake --nbmake-timeout=1200 $(cat diff.txt)
