name: Run all notebooks

on:
  workflow_dispatch:
    inputs:
      notebook-selector:
        description: Relative path to notebooks
        required: false
        type: string

jobs:
  pytest:
    name: Test all notebooks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          sudo apt-get -y install graphviz
          pip install -c .constraints/py3.8.txt .[test]
      - run: |
          case $(pytest --nbmake --nbmake-timeout=1200 ${{ github.event.inputs.notebook-selector }}) in
            0|5) exit 0
            *) exit $1
          esac
        # cspell:ignore esac
