name: Run all notebooks

on:
  workflow_dispatch:
    inputs:
      notebook-selector:
        description: Relative path to notebooks
        required: false
        type: string

jobs:
  pytest:
    name: Test all notebooks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.7 # should match notebook kernel name
      - name: Install dependencies
        run: |
          julia -e 'import Pkg; Pkg.add("IJulia")'
          sudo apt-get -y install graphviz
          pip install -c .constraints/py3.8.txt .[test]
      - name: Install IJulia kernel
        run: |
          julia -e 'using IJulia; installkernel("julia")'
        # cspell:ignore installkernel
      - run: |
          pytest --nbmake --nbmake-timeout=1200 ${{ github.event.inputs.notebook-selector }}
